### ISSUE TITLE
渐进阅读摘录功能建议

### ISSUE THREAD

**Issue by maozhijie** [oflg/Tidme#12]
摘录大量内容时,能否在阅读卡片里保持正确的换行

能否包括摘录的图片

在摘录大量内容是,能否保持正确的深色标注
现状如下
![image](https://github.com/oflg/Tidme/assets/13058274/0bb9a7ed-7d28-40a4-b7ef-6c9d8185749f)

**Comment by oflg** [comment]
1. 目前不能换行，这受限于于官方的dynanonate插件。
2. 目前不能摘录图片，有方法，但是我还没想好怎么样结合更好。
3. 是指只没有标注有文字（也标注了空白），还是说上面的颜色叠加变深了？另外这个只摘录句子，不建议摘录章节。

**Comment by maozhijie** [comment]
> 1. 目前不能换行，这受限于于官方的dynanonate插件。
> 2. 目前不能摘录图片，有方法，但是我还没想好怎么样结合更好。
> 3. 是指只没有标注有文字（也标注了空白），还是说上面的颜色叠加变深了？另外这个只摘录句子，不建议摘录章节。

是指颜色叠加.
其实选中这么多文本的目的不是摘录,是为了把一个大的材料变成更小的可编辑的而且能够溯源的小卡片,这个流程在sm里挺常用的.如果不能这么做会麻烦不少,但是渐进阅读流程还是能跑通的.

**Comment by oflg** [comment]
> 为了把一个大的材料变成多个更小的可编辑的而且能够溯源的小卡片,这个流程在sm里挺常用的.

确实挺需要这个功能。
tidme很久前有版本出过摘录出更小卡片的功能，我想想怎么更好地结合进来吧。
