### ISSUE TITLE
关于在太记中，tidme点击后的牌组选项无法正常使用的情况

### ISSUE THREAD

**Issue by Unword** [oflg/Tidme#13]
![图片](https://github.com/oflg/Tidme/assets/48384420/a8d7e5b9-df68-4968-90ce-de8aa04e5d3c)
![图片](https://github.com/oflg/Tidme/assets/48384420/d920fff6-f223-4bb3-8808-f7f1f67caea2)
图片太长，中间部分我就不放了。
发现在太记中无论是导入还是仅安装插件，在最新的插件状态下，牌组选项出现乱码情况。
尝试搜了一下，很多图片上的代码在实际中的代码完全没出现过，可能是我不怎么懂代码的原因。
希望能修复这个问题。

**Comment by oflg** [comment]
可能是太记的tw核心版本低于5.3.1造成的，需要升级。

**Comment by Unword** [comment]
懂了，大概是太记的tw核心无法主动升级，等到版本更新了再说吧。
