### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by papiche** [oflg/Tidme#14]
Incremental learning seems interesting
I'd like to make a french translation.
Please could you indicate me how to proceed?

**Comment by oflg** [comment]
Welcome!👏 There are three parts to translate and you can choose one or all of them.

## Translate Plugin

1. Fork the https://github.com/oflg/Tidme-zh-Hans repository and **name** it Tidme-fr-FR.
2. Change all Chinese in the repository to French. If you are good at English and don't want to use machine translation for Chinese, you can check English in the `languages` folder of the corresponding plugin in https://github.com/oflg/Tidme/tree/master/src .

## Translate Webiste

1. Fork the https://github.com/oflg/Tidme-website-zh-Hans repository and **name** it Tidme-website-fr-FR.
2. Change all Chinese in the repository to French. If you are good at English and don't want to use machine translation for Chinese, you can check English  in https://github.com/oflg/Tidme/tree/master/wiki/website/index .

## Translate Manual

1. Fork the https://github.com/oflg/Tidme-manual-zh-Hans repository and **name** it Tidme-manual-fr-FR.
2. Change all Chinese in the repository to French. If you are good at English and don't want to use machine translation for Chinese, you can check English  in https://github.com/oflg/Tidme/tree/master/wiki/manual/index.

Once you've finished translating, just @ me in this issue. I'll finish the rest of the writing code part .

**Comment by oflg** [comment]
@papiche I've merged the repository you created into the [dev branch](https://github.com/oflg/Tidme/tree/dev). You can now use [the command](https://github.com/oflg/Tidme/tree/dev#%EF%B8%8Fdevelopment) to translate directly in TiddlyWiki.

**Comment by oflg** [comment]
The French version of Tidme has been released: https://oflg.github.io/Tidme/fr-FR

**Comment by Telumire** [comment]
The translation seem to have issues:

![image](https://github.com/user-attachments/assets/db75ef5f-34d8-402e-bc9d-cad0e2e7b9b1)

> "boudoir" : a woman's dressing room
> noun. bou·​doir ˈbüd-ˌwär ˈbu̇d- : a woman's dressing room, bedroom, or private sitting room. Etymology. from French boudoir "lady's dressing room," literally, "a place to sulk," from bouder "to sulk"15 Jul 2024

I'm willing to help fix the translation errors, do you want me to create a fork or should I contribute to the fork created by @papiche  @oflg ?

**Comment by oflg** [comment]
As you wish.

Thank you for your contribution.
