### ISSUE TITLE
牌组点击开始学习后，挖空题自动显现，不点击也会出来/

### ISSUE THREAD

**Issue by Unword** [oflg/Tidme#15]
![K2G)NL(MTN9LG5@0Z15`8JN](https://github.com/oflg/Tidme/assets/48384420/24111f11-694c-46d1-ba3d-aee9705cda83)
墨屉的牌组点进去开始学习后，这类题目不用点，就自动出来了。用的是摘录句子，最新插件。最新太记。

**Comment by oflg** [comment]
麻烦把这个tid上传到这里，看看原因在哪里。

**Comment by Unword** [comment]
我懂了，好像旧版插件有这个说明。
我新做了个摘录成功了。

**Comment by oflg** [comment]
应该是卡片正面写错了。

要把题目写在caption里，而不是text里。

或者加个reverse字段，来反转卡片 https://oflg.github.io/Tidme/manual/zh-Hans#%E5%A6%82%E4%BD%95%E5%8F%8D%E8%BD%AC%E6%98%BE%E7%A4%BA%E9%97%AE%E9%A2%98%E5%92%8C%E7%AD%94%E6%A1%88%EF%BC%9F。

**Comment by Unword** [comment]
reverse字段加了后，确实可以了，很正常。
不过摘录的卡片，caption是灰色的，不能编辑，如图所示
![图片](https://github.com/oflg/Tidme/assets/48384420/541bced2-536e-42b8-b212-948d0f0f8ba5)
![图片](https://github.com/oflg/Tidme/assets/48384420/33fc2f3a-8607-4f9f-b5a5-4261e4419c2f)

**Comment by oflg** [comment]
caption可以编辑，你试试看。

**Comment by Unword** [comment]
{{||$:/plugins/tidme/read/ui/ViewTemplate/sentence}}
caption这行的意思是显示一行预览是吗？删掉后，少了个标题

**Comment by oflg** [comment]
是的

**Comment by Unword** [comment]
还有问题就是为什么有些挖空题可以点击隐藏，而有些不行，点不动，而预览可以正常隐藏。我看里面的内容都差不多，没什么区别。附tid
![图片](https://github.com/oflg/Tidme/assets/48384420/ba849674-3f99-425d-9289-5045992fe029)

[Desktop.zip](https://github.com/oflg/Tidme/files/13315137/Desktop.zip)

**Comment by oflg** [comment]
本来设计的是条目在展开状态下，填空题不能点击。

这里有bug，导致填空题在条目“直接处于展开状态”下能够点击，条目“从折叠变为展开状态后”不能点击。

**Comment by Unword** [comment]
看起来重启服务能解决这个bug

**Comment by oflg** [comment]
不是重启的问题，本来要设计为展开后**不能**点击。

**Comment by Unword** [comment]
主要是学习过后，再点开来，没有展开效果。我也不大确定还会不会复发
