### ISSUE TITLE
编辑模板caption字段不应是全局实现

### ISSUE THREAD

**Issue by dongrentianyu** [oflg/Tidme#2]
在`$:/config/FieldEditorFilters/tidme/caption`条目里，改成加?标签的。

```
[<storyTiddler>!has:field[caption]then[$:/core/ui/EditTemplate/fieldEditor/default]] ~[<currentTiddler>tag[?]match[caption]then[$:/plugins/tidme/fsrs4tw/ui/EditTemplate/field]]
```

这样的话，就只会卡片条目编辑caption会这样了，其他的不受影响了。

**Comment by dongrentianyu** [comment]
因为我主要是觉得正常的普通条目，不需要使用这种编辑模板。所以理论上应该不需要给其他条目加上模板。不然又会有人问，为什么其他字段不能有这样的模板之类的。

**Comment by dongrentianyu** [comment]
这样修改，好像会取消这个编辑模板，具体的可能是筛选器写错了还是什么。明天再排查一下试试。

我觉得之前的挺好的，不知道能不能保留下，或者让用户进行选择呢？

**Comment by dongrentianyu** [comment]
没搞出来，不知道为什么。唉，可能我还是会用旧版吧，我感觉旧版更适合我一点。点击添加了?标签，就会自动显示编辑模板。

**Comment by oflg** [comment]
> 改成加?标签的。

现在墨屉不再是只对加?标签的有效，对所有牌组有效，只是默认牌组是?标签的。

创建一个牌组后，可以定义要复习的条目，比如可以自定义成x标签的。

![image](https://github.com/oflg/Tidme/assets/42492105/969b54e4-f44f-47e1-bf4c-76ba095ad595)

**Comment by oflg** [comment]
> ~[<currentTiddler>tag[?]

此处的currentTiddler是指字段名称，所以你刚刚改的没有效果。storyTiddler才是条目名称。

**Comment by dongrentianyu** [comment]
```
[<storyTiddler>!has:field[caption]tag[?]then[$:/core/ui/EditTemplate/fieldEditor/default]] ~[<currentTiddler>match[caption]then[$:/plugins/tidme/fsrs4tw/ui/EditTemplate/field]]
```

但我这样写还是不行。

我觉得还是保留原来的编辑模板比较好。

![image](https://github.com/oflg/Tidme/assets/109711900/f8767e0a-1336-444b-be8e-c231a6a1141e)

因为我这种编辑模式下，编辑起来也很好，特别是在需要编写一些多行文本的题目的时候。

另外钓鱼插件是会自动升级成`$:/plugins/tidme/fsrs4tw`插件还是需要手动安装？因为我在cpl里没有看到 `$:/plugins/tidme/fsrs4tw`看到这个插件。

**Comment by dongrentianyu** [comment]
![image](https://github.com/oflg/Tidme/assets/109711900/eeab717f-a581-43d9-ba5f-44f958b57be6)

感觉新旧的两个模板都差不多，虽然我可能更适应旧版本的。

**Comment by oflg** [comment]
喜欢就用老版本吧，或者自己diy，我应该不会改成原来的了。
