### ISSUE TITLE
从牌组里去掉并继续下一个的按钮

### ISSUE THREAD

**Issue by linonetwo** [oflg/Tidme#22]
**Is your feature request related to a problem? Please describe.**

如果发现标签没了，能不能弹出一个隐藏的按钮，从牌组里去掉并继续下一个

![c4a78a4f8fe3d740c3bc56e81d36550e](https://github.com/oflg/Tidme/assets/3746270/7fc6a6f1-acb3-48c2-977a-7a9ee13fc849)

比如我在整理过去的想法的时候刷到一些整理完的，我就把想法标签去掉了。
现在我只好把这个卡片关掉，然后重新开始复习这个牌堆，以便跳过当前卡片。主要是担心点了「简单」的话，下次会不会还轮到这张卡片，还有关于它的记录会不会变成残留数据。

有一个按钮的话还能顺便把卡片上面的复习记录字段给清空？

**Describe the solution you'd like**

当基于某个筛选器获取卡片时，发现条目不再满足这个筛选器，就出现这样的按钮。

**Describe alternatives you've considered**

或者说直接点「简单」就行了，也不会有脏数据，也不会再次出现这张卡？

**Additional context**

用于整理资料的场景

**Comment by linonetwo** [comment]
QQ群里聊了，现在更多菜单里就有一个跳过按钮，那应该是让跳过按钮在检测到当前卡片已不符合筛选器的时候，不加感叹号标签，而是直接跳到下一个卡片

**Comment by oflg** [comment]
理清需求了：跳过时删除特定标签，而不是添加`!`标签。

之前我考虑和写过这个功能，通过用户在派驻的设置里自定义排除功能的action实现。因为目前tw里做不到找出“能够对删选器取反”的特定标签。

下面的图例添加了删除`xxx`标签的功能：

![image](https://github.com/oflg/Tidme/assets/42492105/fe131f1a-4eef-4881-b795-deba0c739858)

**Comment by oflg** [comment]
> 有一个按钮的话还能顺便把卡片上面的复习记录字段给清空？

清空字段记录也可以用上面的方法来，不过比较麻烦要找出Tidme产生了哪些字段。需要的话，以后我在Tidme里提供个能够一次删除tidme产生的字段的action。

**Comment by linonetwo** [comment]
的确是可以用这个动作来自定义，之前我都忘了

**Comment by linonetwo** [comment]
加上了

```xml
{{$:/plugins/tidme/fsrs4tw/buttons/action/exclude}}

<$action-sendmessage $message="tm-remove-tag" $param="想法"/>
```

<img width="592" alt="截屏2024-01-17 13 08 19" src="https://github.com/oflg/Tidme/assets/3746270/8c40fc80-ebe7-4ef4-9084-20c6cd575987">

**Comment by linonetwo** [comment]
<img width="498" alt="截屏2024-01-17 13 10 26" src="https://github.com/oflg/Tidme/assets/3746270/db2b8370-ba64-4aa8-b4e7-e8bcdc5977d3">

字段里有多行内容，条目就会变成 json 格式，印证了 https://github.com/tiddly-gittly/TiddlyWiki-CPL/issues/166

**Comment by oflg** [comment]
是会这样，tw 的机制🤣
