### ISSUE TITLE
标题大小能否自定义或者给出几个大小的选项

### ISSUE THREAD

**Issue by dongrentianyu** [oflg/Tidme#3]
因为不同人可能会有不同需求吧。我是喜欢偏大的字体，这样更能集中注意力到屏幕上。有些人可能会想要更小的字体。之前是通过修改源代码里的`h2`标签，改成`fonte`字体标签实现的。

如果不想太自定义，也可以给出几个选项，大中小之类的，以供选择。

**Comment by oflg** [comment]
我考虑下，目前的做法是。想打就在caption里写上tw只带的!（一级标题）
