### ISSUE TITLE
可以导入包含旧的tiddlymemo数据的tiddlywiki吗

### ISSUE THREAD

**Issue by hffqyd** [oflg/Tidme#31]
请问可以导入之前包含学习过的旧的tiddlymemo数据的tiddlywiki吗？之前使用过旧版本的tiddlymemo，请问现在可以把数据导出再导入到新的Tidme中学习吗？

请问如果把新的Tidme插件直接导入到已有的tiddlywiki中覆盖，可以使用吗？

谢谢！

**Comment by oflg** [comment]
不能完美使用。卡片的会被重新识别为新卡片，填空题也不兼容。

**Comment by hffqyd** [comment]
好的，谢谢。

那有什么比较完美或次完美的解决方法吗？可以不需要完全从头再过一遍的？

可以通过编辑导出的json数据做到吗？

**Comment by oflg** [comment]
不客气。

排期没有办法完美解决（因为算法不兼容，这也是老版不兼容的核心原因）。

把原来的“填空题”“选择题”模板（$:/plugins/oflg/fishing/macros/questions/cloze $:/plugins/oflg/fishing/macros/questions/select）从旧版复制到新版，就能解决问题模板无法识别的问题。

**Comment by hffqyd** [comment]
好的，非常感谢~
