### ISSUE TITLE
感觉有些卡顿，是因为计时器还是啥原因

### ISSUE THREAD

**Issue by Zacharia2** [oflg/Tidme#4]

**Comment by Zacharia2** [comment]
可能是时间更新的太过频繁？

**Comment by oflg** [comment]
有可能。

也有可能是因为调用算法和筛选器过多造成的。

![image](https://github.com/oflg/Tidme/assets/42492105/ac22052c-2a31-4d9c-a798-fc3d96ef7253)

每次只留一个卡片（不留牌组界面）在故事河里应该会减少卡顿。

**Comment by oflg** [comment]
尝试修复了下，应该是好了点。

调用fsrs算法的次数：从每个评分按钮一次，改为了四个评分按钮共一次。
