### ISSUE TITLE
新版本是把渐进阅读移除了吗？

### ISSUE THREAD

**Issue by zxhd863943427** [oflg/Tidme#5]
我发现新版本好像没有渐进阅读功能了。

**Comment by oflg** [comment]
正在开发哈

**Comment by zxhd863943427** [comment]
哎呀，居然没发现，很抱歉。
话说这个重构的用意是什么？以及会支持图片摘录吗？

**Comment by oflg** [comment]
> 哎呀，居然没发现，很抱歉。

没事哈。

> 话说这个重构的用意是什么？

重构是因为主插件（fsrs4tw）更新了fsrs算法与旧版不兼容，并且目前摘录插件存在性能差、有时候选择失控（比如一不小心会选择全部）的问题。用意是更好的用户体验。

> 以及会支持图片摘录吗？

可以做，只是要想一个好一点的方法，所以不确定这一次支不支持。

**Comment by oflg** [comment]
已发布摘录阅读插件，插件库里直接安装即可。

https://github.com/oflg/Tidme/releases/tag/v1.5.0

**Comment by zxhd863943427** [comment]
测试了一下，这个版本还没有tpub集成，有点可惜，不过可以先手动操作。

但是这个是刚需了：
![图片](https://github.com/oflg/Tidme/assets/74853597/525cd70b-2540-4b12-a751-a4db381c115e)

还有，两个版本似乎都没有保留换行符？

**Comment by oflg** [comment]
> 没有保留换行符？

摘录功能依赖于tw的dynannotate插件，它没有保留换行符和图片等富文本，所以不支持。（墨屉最初用的是tw内的剪切按钮，支持富文本。但是要先点编辑进入编辑器内进行摘录，所以改成了现在这样）

**Comment by zxhd863943427** [comment]
>这个案例只在nodejs上实现了，单文件会报错。所以还是继续twpub吧。🤣

啊这……其实除了测试外，我主要还是使用tidGI-desktop来处理多个tiddlywiki。这个功能会与twpub冲突吗？不会的话能否考虑保留？

**Comment by oflg** [comment]
不会冲突，twpub也是用这种方法在nodejs上构建的，殊途同归。

因为这样的插件在单文件使用必报错，还有几个依赖插件，想安装好挺费事，用起来没那么舒服，所以但是不保留了。

**Comment by gaoluji** [comment]
> 不会冲突，twpub也是用这种方法在nodejs上构建的，殊途同归。
> 
> 因为这样的插件在单文件使用必报错，还有几个依赖插件，想安装好挺费事，用起来没那么舒服，所以还是不保留了。

不保留渐进阅读了？

**Comment by oflg** [comment]
已支持twpub，插件库里直接安装即可。

https://github.com/oflg/Tidme/releases/tag/v1.9.0

**Comment by gaoluji** [comment]
> 已支持twpub，插件库里更新即可。
> 
> https://githubfast.com/oflg/Tidme/releases/tag/v1.9.0

还是无啊……

**Comment by oflg** [comment]
在这里

![image](https://github.com/oflg/Tidme/assets/42492105/74d5bc24-eec1-47f4-8f2b-62129e016178)

**Comment by gaoluji** [comment]
> 在这里
> 
> ![image](https://usercontent.githubfast.com/user-images/42492105/274454791-74d5bc24-eec1-47f4-8f2b-62129e016178.png)

ok

**Comment by zxhd863943427** [comment]
twpub集成貌似只能读取从twpub库中下载的书籍，手动导入的json识别不了。

**Comment by oflg** [comment]
> 手动导入的json识别不了

确实，我修下。

**Comment by oflg** [comment]
已修复，插件库里更新即可。

https://github.com/oflg/Tidme/releases/tag/v1.9.1
