### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '$:/plugins/tidme/fsrs4tw/buttons/action/options')

### ISSUE THREAD

**Issue by dongrentianyu** [oflg/Tidme#6]
![image](https://github.com/oflg/Tidme/assets/109711900/51ee2d41-fe5b-4c14-acb3-9e7a8f0ab129)

![image](https://github.com/oflg/Tidme/assets/109711900/a9d6eb7b-05ad-4a0e-96a7-b6d3ede52fb1)

不太清楚是什么bug，先留下控制台展示的内容。

**Comment by oflg** [comment]
方便说一下怎么操作的吗？我试试复现找bug

**Comment by dongrentianyu** [comment]
我删除了一个牌组，然后又点击生成一个新的牌组，就出现这个bug了。

**Comment by oflg** [comment]
已找到bug并修复： https://github.com/oflg/Tidme/releases/tag/v1.4.1

这个bug是创建牌组后自动弹窗产生的。但是我没有找出具体原因，于是删除了这个功能。
