### ISSUE TITLE
关于渐进阅读单词的闪卡样式改进

### ISSUE THREAD

**Issue by gaoluji** [oflg/Tidme#8]
在墨屉中实现英语单词的增量阅读效果非常好。
但单词的复习卡片个人感觉可以更改。
## 说明：单词总是在言语（言说、使用）中产生意义
通常的单词复习界面是——单词》释义》（或许我们会去看它的例句）。
而实际上，真正有效的使用单词恰恰实在实际的语言环境中，一句话被说完，我们才能理解各个单词在句子中都是什么意义。（一个单词可能拥有很多意义，但在实际语境中，它是这个意思）。
所以，有效的学习单词是——**句子（语境）》单词》释义**（这个释义通常是单一的）
## 个人anki实现的效果
![image](https://github.com/oflg/Tidme/assets/139356383/bf364509-2691-49f9-858e-31c9a11e81f2)
![image](https://github.com/oflg/Tidme/assets/139356383/9b766272-40d8-474a-8c6f-2ec894f6a425)
这是在我阅读的过程中制作的卡片（使用了浏览器插件“在线词典助手”实现的，卡片模板是我自己制作）
## 制卡示范
![image](https://github.com/oflg/Tidme/assets/139356383/ef19df84-e5c6-4ee5-8fc6-eb3ea3503102)
对不认识的单词查词，点旁边的加号进行制卡，自动导入所学单词所在的例句，以及释义。
## 在墨屉中实现的想法
在墨屉中对不认识的单词进行标记后，这个单词在所有文章都会被标识。
同时单词制卡，应当是——目前单词所在的句子，卡片的问题是：这个句子中这个单词的释义是什么（单词在这个句中的释义是什么）
如何管理句子？
我想的是通过双链——一个单词应当是双链被放在一个wiki中“[[单词]]”，有多少个句子归属于这个单词。
这样管理单词就能知道目前遇到了多少个用法。
并且我们所学到的单词用法越多（也就是这个单词的句子越多），句子的颜色也会被改变，我们正在逐渐把握这个单词，我们学会了它的不同用法。通常的单词软件我们只是学习这个单词的意思，而没有真正学会使用这个单词，大多数人在句子见到这个单词还是用不来（我和我的朋友都深受此困扰）。

**Comment by oflg** [comment]
想法很不错，我研究研究。

**Comment by gaoluji** [comment]
> 想法很不错，我研究研究。

我在想词组咋实现，而且有时候一个词组是分开的

**Comment by gaoluji** [comment]
> 想法很不错，我研究研究。

词组我知道咋办了，大致实现方式
先拖动鼠标，把这些都先划起来，然后右键，出现个大致页面用于选词

**Comment by oflg** [comment]
此功能已发布，你在插件库里更新下即可尝试。

https://github.com/oflg/Tidme/releases/tag/v1.10.0

![image](https://github.com/oflg/Tidme/assets/42492105/3af3579e-c36d-4ae1-ba0e-8ca6fe99a031)
![image](https://github.com/oflg/Tidme/assets/42492105/e91f1701-60c6-4fa3-8b6c-187b243b8e9c)
